// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxqpE6_RzK6PocFf-RhHwc3Ng654ZWKo',
    appId: '1:458080390477:web:ddec16c19c98fbb2e5fb04',
    messagingSenderId: '458080390477',
    projectId: 'flutter-app-e3653',
    authDomain: 'flutter-app-e3653.firebaseapp.com',
    storageBucket: 'flutter-app-e3653.firebasestorage.app',
    measurementId: 'G-HKB8SPR1ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIoEmVpeYB4F-PmqhGfwXMAGPKTTxuSTg',
    appId: '1:458080390477:android:7611162e0c070543e5fb04',
    messagingSenderId: '458080390477',
    projectId: 'flutter-app-e3653',
    storageBucket: 'flutter-app-e3653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHsDDV6rK_6X7YNY4Neysn-GcYlsMQjyI',
    appId: '1:458080390477:ios:e3db1f48700182bce5fb04',
    messagingSenderId: '458080390477',
    projectId: 'flutter-app-e3653',
    storageBucket: 'flutter-app-e3653.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHsDDV6rK_6X7YNY4Neysn-GcYlsMQjyI',
    appId: '1:458080390477:ios:e3db1f48700182bce5fb04',
    messagingSenderId: '458080390477',
    projectId: 'flutter-app-e3653',
    storageBucket: 'flutter-app-e3653.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxqpE6_RzK6PocFf-RhHwc3Ng654ZWKo',
    appId: '1:458080390477:web:7ee48ff7104de9f6e5fb04',
    messagingSenderId: '458080390477',
    projectId: 'flutter-app-e3653',
    authDomain: 'flutter-app-e3653.firebaseapp.com',
    storageBucket: 'flutter-app-e3653.firebasestorage.app',
    measurementId: 'G-S8J4QLRMX2',
  );

}